<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RenderLab.Functional\RenderLab.Functional.csproj" />
    <ProjectReference Include="..\RenderLab.Assets\RenderLab.Assets.csproj" />
    <ProjectReference Include="..\RenderLab.Ui\RenderLab.Ui.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
